title = "Pantaloche"
baseURL = "https://insasio.github.io"
tags = ["portfolio", "code", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "Pantaloche blog"
    author = "Inasio"
    description = "Random ramblings and stuff"
    logoBig = "/images/cat1.png"
    logoSmall = "/images/eyes_cat.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/halcon1.png"
    twitter = ""
    linkedin = ""
    github = "inasio"
    email = ""
    googleTagManger = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Work"
    url  = "/#work"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
